config/routes.rb
Rails.application.routes.draw do
  get 'projects/:id/team_memberships', to: "projects#team_memberships"
  resources :team_memberships, only: [:destroy]
  authenticate :user, ->(user) { user.admin? } do
    root 'pages#developer', as: :admin_authenticated_root
  end
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end
  devise_for :users
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :documents, except: [:new, :create, :edit, :update]
  resources :projects, except: [:destroy] do
    resources :team_memberships, only: [:create]
    resources :lists, only: [:new, :create, :index, :update]
    resources :documents, only: [:index, :new, :create, :edit, :update]
  end
  resources :quotes, except: [:new, :create] do
    member do
      patch :submit_for_acceptance
      patch :accept
      patch :reject
    end
    resources :tasks, only: [:create]
  end
  resources :lists, except: [:new, :create, :index, :update] do
    resources :quotes, only: [:new, :create]
    resources :tasks, only: [:new, :create] do
      member do
        get :complete
        get :uncomplete
      end
    end
  end
  resources :tasks, except: [:create, :new] do
    resources :periods, only: [:create, :new]
  end
  resources :notes, only: [:create, :update, :destroy]
  resources :periods, only: [:show, :update, :index] do
    member do
      patch :finish
      patch :accept
    end
  end
  get '/promise/', to: 'pages#promise'
  resources :invoices do
    member do
      patch :approve
    end
  end
  resources :users, only: [:edit, :update]
  get 'profile', to: 'pages#profile'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :tasks
  has_many :notes, as: :noteable, dependent: :destroy
  belongs_to :list
  has_rich_text :description
  validates :name, presence: true

  def color
    case self.status
    when "pending"
      "orange"
    when "rejected"
      "red"
    when "accepted"
      "green"
    when "awaiting acceptance"
      "orange"
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :submit_for_acceptance, :accept, :reject]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.list = List.find(params[:list_id])
    authorize @quote
    if @quote.save
      redirect_to @quote, notice: 'Quote was successfully created.'
    else
      flash[:notice] = "Please provide a name for your quote"
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def submit_for_acceptance
    @quote.update(status: "awaiting acceptance", rejected_reason: nil)
    redirect_to @quote
  end

  def accept
    @quote.update(status: "accepted", rejected_reason: nil)
    @quote.tasks.update_all(approved: true)
    redirect_to @quote
  end

  def reject
    @quote.update(status: "rejected", rejected_reason: quote_params[:rejected_reason])
    redirect_to @quote
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = Quote.find(params[:id])
    authorize @quote
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.require(:quote).permit(:status, :total, :name, :description, :rejected_reason)
  end
end

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :status %>
    <%= f.input :total %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.status %></td>
        <td><%= quote.total %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<div class="container">
  <div class="backed mt-4">
    <h3 class="text-center"><%= @quote.name %></h3>
    <h5 class="text-center" style="color: <%= @quote.color %>"><%= @quote.status %></h5>
    <p class="text-center"><%= @quote.rejected_reason %></p>
    <%= @quote.description %>
    <div class="row mt-4 mb-1">
      <div class="col-6"><strong>Name</strong></div>
      <div class="col-3"><strong>Duration</strong></div>
      <div class="col-3"><strong>Price</strong></div>
    </div>
    <% @quote.tasks.each do |task| %>
      <div class="sub-backed">
        <div class="row">
          <div class="col-6"><%= task.name %></div>
          <div class="col-3"><%= @quote.readable_length(task.length) %></div>
          <div class="col-3"><%= @quote.humanized_total(task.price) %></div>
        </div>
      </div>
    <% end %>
    <div class="row mt-2 mb-4">
      <div class="col-6"><strong>Total:</strong></div>
      <div class="col-3"><strong><%= @quote.readable_length(@quote.tasks.sum(&:length)) %></strong></div>
      <div class="col-3"><strong><%= @quote.humanized_total(@quote.tasks.sum(&:price)) %></strong></div>
    </div>
    <hr>
    <% if policy(@quote).accept? && @quote.status == "awaiting acceptance" %>
      <div class="jc mb-4">
        <%= link_to accept_quote_path(@quote), method: :patch do %>
          <div class="btn btn-primary">Accept</div>
        <% end %>
      </div>
      <p class="text-center">Or</p>
      <%= form_for(@quote, url: reject_quote_path) do |f| %>
        <%= f.text_field :rejected_reason, placeholder: "Why are you rejecting thgis quote?" %>
        <%= f.submit "Reject" %>
      <% end %>
    <% end %>
    <% if policy(@quote).submit_for_acceptance? && (@quote.status == "pending" || @quote.status == "rejected") %>
      <div class="fe mb-4">
        <%= link_to submit_for_acceptance_quote_path(@quote), method: :patch do %>
          <div class="btn btn-primary">Submit for approval</div>
        <% end %>
      </div>
      <%= simple_form_for [@quote, Task.new] do |f| %>
       <%= f.error_notification %>
       <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

       <div class="form-inputs">
         <h4 class="blue">Add a new task</h4>
         <hr>

         <%= f.input :name, placeholder: "Let's give this task a name", label: false %>
         <%= f.input :description, placeholder: "Perhaps a brief description too...", label: false %>
         <%= f.input :length, placeholder: "Projected time for this task in minutes", label: false %>
         <div class="js">
           <input type="date" class="form-control w50" id= "completed_by" name="task[completed_by]" label= "completed_by">
           <p class="mb-0 w50 pl-2">Needs to be completed by?</p>
         </div>

         <!-- ASSIGN TEAM MEMBERS -->
         <div class="form-group mt-4">
           <input type="hidden" name="task[user_ids][]" value="">
           <div class="category-choices">
             <% @quote.list.project.valid_members.each do |user| %>
               <label class="category-choice jca" title="<%= user.full_name %>" style="background-image: url('<%= user.photo.attached? ? url_for(user.photo) : "" %>'); background-color: <%= user.color %>">
                 <p class="text-center bold m-0"><%= user.initials if !user.photo.attached? %></p>
               </label>
               <input type="checkbox" class="hdchekbox mr-2" value="<%= user.id %>" name="task[user_ids][]" id="task_user_ids_<%= user.id %>">
             <% end %>
             <p>Assign this task to any users?<p>
            </div>
         </div>

       </div>

       <div class="jc mt-4">
         <%= f.button :submit, class: 'btn btn-primary' %>
       </div>
      <% end %>
    <% end %>
  </div>
  <% @quote.notes.order(created_at: :desc).each do |note| %>
    <%= render "shared/note", note: note %>
  <% end %>
  <hr>
  <div class="sub-note">
    <%= render "notes/form", note: Note.new, noteable: @quote %>
  </div>
</div>