config/routes.rb
Rails.application.routes.draw do
  get 'projects/:id/team_memberships', to: "projects#team_memberships"
  resources :team_memberships, only: [:destroy]
  authenticate :user, ->(user) { user.admin? } do
    root 'pages#developer', as: :admin_authenticated_root
  end
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end
  devise_for :users
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :documents, except: [:new, :create, :edit, :update]
  resources :projects, except: [:destroy] do
    resources :team_memberships, only: [:create]
    resources :lists, only: [:new, :create, :index, :update]
    resources :documents, only: [:index, :new, :create, :edit, :update]
  end
  resources :quotes, except: [:new, :create] do
    member do
      patch :submit_for_acceptance
      patch :accept
      patch :reject
    end
    resources :tasks, only: [:create]
  end
  resources :lists, except: [:new, :create, :index, :update] do
    resources :quotes, only: [:new, :create]
    resources :tasks, only: [:new, :create] do
      member do
        get :complete
        get :uncomplete
      end
    end
  end
  resources :tasks, except: [:create, :new] do
    resources :periods, only: [:create, :new]
  end
  resources :notes, only: [:create, :update, :destroy]
  resources :periods, only: [:show, :update, :index] do
    member do
      patch :finish
      patch :accept
    end
  end
  get '/promise/', to: 'pages#promise'
  resources :invoices do
    member do
      patch :approve
    end
  end
  resources :users, only: [:edit, :update]
  get 'profile', to: 'pages#profile'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :list
  belongs_to :quote, optional: true
  belongs_to :invoice, optional: true

  has_many :periods, dependent: :destroy
  has_many :user_tasks, dependent: :destroy
  has_many :users, through: :user_tasks
  has_many :notes, as: :noteable, dependent: :destroy

  validates :name, presence: true
  before_save :set_price
  before_save :set_approved

  def set_approved
    list.payment_type == "qouted" ? false : true
  end

  def payment_type
    list.payment_type
  end

  def total_length
    sum = 0
    periods.each { |r| sum += r.current_length }
    sum
  end

  def total_price
    sum = 0
    periods.each { |r| sum += r.price }
    sum
  end

  def set_price
    if self.payment_type == "support"
      self.price = self.periods.sum(&:price)
      self.length = self.periods.sum(&:length)
    elsif self.payment_type == "emergency"
      if self.faulty == true
        self.price = 0
      else
        self.price = self.periods.sum(&:price)
        self.length = self.periods.sum(&:length)
      end
    elsif self.payment_type == "my_tasks"
      0
    end
  end

  def complete
    self.update!(completed: true, invoice: self.list.project.current_invoice)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :uncomplete, :complete]
  before_action :set_list, only: [:create]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = policy_scope(Task)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    authorize @task
  end

  # GET /tasks/1/edit
  def edit
  end

  def complete
    @task.update(completed: true, completed_at: Time.now, invoice: @task.list.project.current_invoice)
    respond_to do |format|
      format.html { redirect_to project_lists_path(@task.list.project)}
      # format.js
    end
  end

  def uncomplete
    @task.update(completed: false, completed_at: nil, invoice: nil)
    respond_to do |format|
      format.html { redirect_to project_lists_path(@task.list.project)}
      # format.js
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.list = @list
    do_quote_stuff if @quote
    authorize @task
    @tasks = @list.tasks
    if @task.save
      params[:task][:user_ids].reject{|r| r == ""}.each do |id|
        UserTask.create(task: @task, user_id: id.to_i)
      end
      if @quote
        redirect_to quote_path(@quote)
      else
        redirect_to project_lists_path(@project)
      end
      flash[:notice] =  'Task was successfully created.'
    else
      if @quote
        render "quotes/show"
      else
        redirect_to project_lists_path(@project)
      end
      flash[:notice] =  'Please give your task a name'
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def do_quote_stuff
    @task.quote = @quote
    @task.price = @task.length / 60.0 * 4000
  end

  def set_list
    if params[:quote_id]
      @quote = Quote.find(params[:quote_id])
      @list = @quote.list
    else
      @list = List.find(params[:list_id])
    end
    @project = @list.project
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
    authorize @task
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:list_id, :name, :description, :completed_by, :completed, :length, :price, :user_ids)
  end
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :list %>
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.list_id %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="top-header">
  <h3 class="text-center"><%= link_to @task.list.project.name, project_path(@task.list.project), class: 'secondary' %> | <%= link_to @task.list.name, list_path(@task.list), class: 'secondary' %> | <%= @task.name %></h3>
</div>
<div class="container">
  <div class="backed nomin">
    <%= render "shared/task", task: @task, index: 0 %>
  </div>
</div>