config/routes.rb
Rails.application.routes.draw do
  get 'projects/:id/team_memberships', to: "projects#team_memberships"
  resources :team_memberships, only: [:destroy]
  authenticate :user, ->(user) { user.admin? } do
    root 'pages#developer', as: :admin_authenticated_root
  end
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end
  devise_for :users
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :documents, except: [:new, :create, :edit, :update]
  resources :projects, except: [:destroy] do
    resources :team_memberships, only: [:create]
    resources :lists, only: [:new, :create, :index, :update]
    resources :documents, only: [:index, :new, :create, :edit, :update]
  end
  resources :quotes, except: [:new, :create] do
    member do
      patch :submit_for_acceptance
      patch :accept
      patch :reject
    end
    resources :tasks, only: [:create]
  end
  resources :lists, except: [:new, :create, :index, :update] do
    resources :quotes, only: [:new, :create]
    resources :tasks, only: [:new, :create] do
      member do
        get :complete
        get :uncomplete
      end
    end
  end
  resources :tasks, except: [:create, :new] do
    resources :periods, only: [:create, :new]
  end
  resources :notes, only: [:create, :update, :destroy]
  resources :periods, only: [:show, :update, :index] do
    member do
      patch :finish
      patch :accept
    end
  end
  get '/promise/', to: 'pages#promise'
  resources :invoices do
    member do
      patch :approve
    end
  end
  resources :users, only: [:edit, :update]
  get 'profile', to: 'pages#profile'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_assignees_row.html.erb
<div class="jc ml-2">
  <% users.each do |user| %>
    <div class="avatar-sm jar no-z" title='<%= "#{user.full_name}" %>' style="background-image: url('<%= user.photo.attached? ? url_for(user.photo) : "" %>'); background-color: <%= user.color %>">
       <p class="text-center bold m-0"><%= user.initials if !user.photo.attached? %></p>
    </div>
  <% end %>
</div>

app/views/shared/_complete_period.html.erb
<p style="color: green;"><%= period.title %></p>

app/views/shared/_developer_tasks.html.erb
<% tasks.each do |task| %>
  <%= link_to task.name, task_path(task), class: "task_link" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_hidden_quote_form.html.erb
<%= simple_form_for [list, Quote.new], html: { id: "quote_form_#{list.id}", class: "task-form mt-2" } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h4 class="blue">Request a quote</h4>
    <hr>

    <%= f.input :name, placeholder: "Let's give this quote a name", input_html: {id: "name_#{list.id}" }, label: false %>
  </div>
  <p>Please add any additional information or documents below</p>
  <%= f.rich_text_area :description %>
  <div class="jc mt-4">
    <%= f.button :submit, class: 'btn btn-primary', id: "confirm_#{list.id}" %>
    <div class="btn btn-tertiary ml-2" id="hide_task_<%= list.id %>">
      Cancel
    </div>
  </div>
<% end %>
<div class="line-link showme mb-2" id="new_task_<%= list.id %>">
  <i class="fas fa-plus blue"></i>
</div>




<script>
  document.getElementById('new_task_<%= list.id %>').addEventListener('click', (e) => {
    document.getElementById('quote_form_<%= list.id %>').classList.add('high')
    e.target.classList.add('hide')
  })
  document.getElementById('hide_task_<%= list.id %>').addEventListener('click', (e) => {
    document.getElementById('quote_form_<%= list.id %>').classList.remove('high')
    document.getElementById('new_task_<%= list.id %>').classList.remove('hide')
  })
  document.getElementById('confirm_<%= list.id %>').addEventListener('click', (e) => {
    if (document.getElementById('name_<%= list.id %>').value == "") {
      e.preventDefault()
      document.getElementById('name_<%= list.id %>').classList.add("shake")
      setTimeout(function(){ document.getElementById('name_<%= list.id %>').classList.remove("shake"); }, 1000);
    }
  })
</script>

app/views/shared/_hidden_task_form.html.erb
<%= simple_form_for [list, Task.new], html: { id: "task_form_#{list.id}", class: "task-form mt-2" }, remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h4 class="blue">Add a new task</h4>
    <hr>

    <%= f.input :name, placeholder: "Let's give this task a name", input_html: {id: "name_#{list.id}" }, label: false %>
    <%= f.input :description, placeholder: "Perhaps a brief description too...", label: false %>
    <div class="js">
      <input type="date" class="form-control w50" id= "completed_by" name="task[completed_by]" label= "completed_by">
      <p class="mb-0 w50 pl-2">Needs to be completed by?</p>
    </div>

    <!-- ASSIGN TEAM MEMBERS -->
    <div class="form-group mt-4">
      <input type="hidden" name="task[user_ids][]" value="">
      <div class="category-choices">
        <% list.project.valid_members.each do |user| %>
          <label class="category-choice jca" title="<%= user.full_name %>" style="background-image: url('<%= user.photo.attached? ? url_for(user.photo) : "" %>'); background-color: <%= user.color %>">
            <p class="text-center bold m-0"><%= user.initials if !user.photo.attached? %></p>
          </label>
          <input type="checkbox" class="hdchekbox mr-2" value="<%= user.id %>" name="task[user_ids][]" id="task_user_ids_<%= user.id %>">
        <% end %>
        <p>Assign this task to any users?<p>
       </div>
    </div>

  </div>

  <div class="jc mt-4">
    <%= f.button :submit, class: 'btn btn-primary', id: "confirm_#{list.id}" %>
    <div class="btn btn-tertiary ml-2" id="hide_task_<%= list.id %>">
      Cancel
    </div>
  </div>
<% end %>
<div class="line-link showme mb-2" id="new_task_<%= list.id %>">
  <i class="fas fa-plus blue"></i>
</div>




<script>
  document.getElementById('new_task_<%= list.id %>').addEventListener('click', (e) => {
    document.getElementById('task_form_<%= list.id %>').classList.add('high')
    e.target.classList.add('hide')
  })
  document.getElementById('hide_task_<%= list.id %>').addEventListener('click', (e) => {
    document.getElementById('task_form_<%= list.id %>').classList.remove('high')
    document.getElementById('new_task_<%= list.id %>').classList.remove('hide')
  })
  document.getElementById('confirm_<%= list.id %>').addEventListener('click', (e) => {
    if (document.getElementById('name_<%= list.id %>').value == "") {
      e.preventDefault()
      document.getElementById('name_<%= list.id %>').classList.add("shake")
      setTimeout(function(){ document.getElementById('name_<%= list.id %>').classList.remove("shake"); }, 1000);
    }
  })
</script>

app/views/shared/_list_line.html.erb
<div class="container">
  <div class="line-cont">
    <h3 class="help" title="<%= list.type_info %>"><%= list.type_emoji %></h3>
    <div class="line green-line"></div>
    <h3 class="secondary text-center list-title <%= 'collapsed' unless index == 0  %>" data-toggle="collapse" data-target="#collapse_<%= list.id %>" aria-expanded="<%= index == 0 ? true : false %>" aria-controls="collapse_<%= list.id %>">
      <%= list.name %><span class="ml-2 <%= 'blue' if list.incomplete_tasks.length == 0  %>"><%= list.tasks.length - list.incomplete_tasks.length %>/<%= list.tasks.length %></span>
    </h3>
    <div class="line green-line"></div>
    <% if action_name == "index" %>
      <%= link_to list_path(list), class: "list-line-link" do %>
        <i class="fas fa-eye green"></i></h5>
      <% end %>
    <% else %>
      <%= link_to edit_list_path(list), class: "list-line-link" do %>
        <i class="fas fa-edit"></i></h5>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_member_row.html.erb
<div class="<%= delete ? 'js' : 'jc' %>">
  <% if delete %>
    <% memberships.each do |membership| %>
      <%= link_to team_membership_url(membership), method: :delete, class: "nodec", data: { confirm: "Are you sure you want to remove #{membership.user.first_name}" } do %>
        <div class="avatar-sm point <%= membership.relation %>" title='<%= "Remove #{membership.user.full_name}? 😥" %>' style="background-image: url('<%= membership.user.photo.attached? ? url_for(membership.user.photo) : "" %>'); background-color: <%= membership.user.color %>" >
          <p class="text-center point bold m-0"><%= membership.user.initials if !membership.user.photo.attached? %></p>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <% memberships.each do |membership| %>
      <div class="avatar-sm <%= membership.relation %>" title='<%= "#{membership.user.full_name} - #{membership.pretty_relation}" %>' style="background-image: url('<%= membership.user.photo.attached? ? url_for(membership.user.photo) : "" %>'); background-color: <%= membership.user.color %>" >
        <p class="text-center bold m-0"><%= membership.user.initials if !membership.user.photo.attached? %></p>
      </div>
    <% end %>
  <% end %>

  <!-- TO SHOW PLUS BUTTON ON TEAM MEMBERSHIPS PAGE -->
  <% unless delete || hide_add %>
    <%= link_to project_team_memberships_path(@project), class: "line-link member-link" do %>
      <div class="fas fa-plus blue"></div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <% if user_signed_in? %>
    <%= render "shared/lhs_nav" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="avatar-sm jar no-z navbar-avatar dropdown-toggle" title='<%= "#{current_user.full_name}" %>' style="background-image: url('<%= current_user.photo.attached? ? url_for(current_user.photo) : "" %>'); background-color: <%= current_user.color %>" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <p class="text-center bold m-0"><%= current_user.initials if !current_user.photo.attached? %></p>
        </div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_note.html.erb
<div class="note">
  <div class="avatar-sm note-avatar" title='<%= "#{note.user.full_name}" %>' style="background-image: url('<%= note.user.photo.attached? ? url_for(note.user.photo) : "" %>'); background-color: <%= note.user.color %>" >
    <p class="text-center bold"><%= note.user.initials if !note.user.photo.attached? %></p>
  </div>
  <div class="note-content sub-note">
    <div class="jbtwn">
      <p><strong><%= note.user.first_name %></strong>, <%= note.user.position %></p>
      <div class="subtext"><%= note.created_at.strftime("%I:%M %a %m/%d") %></div>
    </div>
    <div class="trix-content p-2"><%= note.content %></div>
  </div>
</div>

app/views/shared/_period_sub.html.erb
<div class="jc">
  <!-- TASK TYPE -->
  <div class="sub-hol">
    <h5 class="ml-3 mr-3"><span class="subtext">task type</span><br><%= period.task.list.type_emoji %></h5>
  </div>

  <!-- SPRINT TIME -->
  <div class="sub-hold">
    <% if period.end_time %>
      <h5 class="ml-3 mr-3"><span class="subtext">time spent this sprint</span><br><%= period.readable_length(period.length) %></h5>
    <% else %>
      <h5 class="ml-3 mr-3"><span class="subtext">time spent this sprint</span><br><%= period.readable_length(period.current_length) %></h5>
    <% end %>
  </div>

  <!-- FREE -->
  <% if period.task.list.payment_type == "free" %>%>
  <div class="sub-hold">
    <h5><span class="subtext">total</span><br><span class="green">My Tasks</span></h5>
  </div>
  <% end %>

  <!-- QUOTED <--->
  <% if period.task.list.payment_type == "quoted" %>
    <div class="sub-hold">
      <h5 class="ml-3 mr-3"><span class="subtext">target time for task</span><br><%= period.readable_length(period.task.total_length) %></h5>
    </div>
    <div class="sub-hold">
      <h5 class="ml-3 mr-3"><span class="subtext">time spent so far</span><br><span class="<%= period.current_length < period.task.total_length ? 'red' : 'green' %>"><%= period.readable_length(period.task.total_length) %></span></h5>
    </div>
  <% end %>

  <!-- SUPPORT -->
  <% if period.task.list.payment_type == "support" %>
    <div class="sub-hold">
      <h5 class="ml-3 mr-3"><span class="subtext">rate</span><br>£<%= period.user.hourly_rate %>/hr</h5>
    </div>
    <div class="sub-hold">
      <h5><span class="subtext">total</span><br><strong><%= period.humanized_total %></strong></h5>
    </div>
  <% end %>
</div>

app/views/shared/_pros_and_cons_row.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 mb-4">
    <div class="sub-backed sub-col">
      <h5 class="text-center pt-2">Emergency</h5>
      <hr class="hr">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-center psm green">Pros</p>
          <p class="text-center psm">Goes to the top of our priority list</p>
          <p class="text-center psm">Rapid response</p>
        </div>
        <div class="col-sm-6">
          <p class="text-center psm red">Cons</p>
          <p class="text-center psm">More expensive if we did not cause the error</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 mb-4">
    <div class="sub-backed sub-col">
      <h5 class="text-center pt-2">Quoted</h5>
      <hr class="hr">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-center psm green">Pros</p>
          <p class="text-center psm">Tasks are performed for a fixed price</p>
        </div>
        <div class="col-sm-6">
          <p class="text-center psm red">Cons</p>
          <p class="text-center psm">Slower, a price must be agreed before work commences</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 mb-4">
    <div class="sub-backed sub-col">
      <h5 class="text-center pt-2">Support</h5>
      <hr class="hr">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-center psm green">Pros</p>
          <p class="text-center psm">Good for small changes and updates</p>
          <p class="text-center psm">Reduced hourly rate with a support contract</p>
        </div>
        <div class="col-sm-6">
          <p class="text-center psm red">Cons</p>
          <p class="text-center psm">Work is billed hourly, may not be ideal for large tasks</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 mb-4">
    <div class="sub-backed sub-col">
      <h5 class="text-center pt-2">My Tasks</h5>
      <hr class="hr">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-center psm green">Pros</p>
          <p class="text-center psm">Tasks are not charged</p>
          <p class="text-center psm">Good for your own tasks, and testing out the platform</p>
        </div>
        <div class="col-sm-6">
          <p class="text-center psm red">Cons</p>
          <p class="text-center psm">Tasks requiring development will not be performed</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tasks.html.erb
<div class="accordion p-0-2" id="listAccordionExample_<%= list.id %>">
  <% if !current_user.accepts_promise %>
    <%= render "shared/unpromised_#{list.payment_type}_list", list: list %>
  <% elsif list.tasks.empty? %>
    <h5><%= list.support_prompt %></h5>
    <h5>👇</h5>
  <% elsif list.incomplete_tasks.empty? %>
    <h5>All tasks complete 🎉</h5>
  <% else %>
    <% list.tasks.where(completed: false).each_with_index do |task, index| %>
      <%= render "shared/task", task: task, index: index %>
    <% end %>
  <% end %>
  <% if list.payment_type == "quoted" %>
    <%= render 'shared/hidden_quote_form', list: list %>
  <% else %>
    <%= render 'shared/hidden_task_form', list: list %>
  <% end %>
  <% list.tasks.where(completed: true).order(completed_at: :asc).each_with_index do |task, index| %>
    <%= render "shared/complete_task", task: task, index: index %>
  <% end %>
</div>

app/views/shared/_unpromised_emergency_list.html.erb
<div class="void_list">

  <h4 class="text-center mb-4">If your site has gone down ☠️ or something is breaking 🤯 and it urgently needs fixing you should report it here.</h4>

  <p>Your team will be <strong>notified immediately</strong> 🚨 and the task will go straight the <strong>top of their priority list</strong> 🔝 </p>

  <p>If our <strong>faulty code</strong> has caused the error 🙈, or your site is <strong>within its warranty</strong> 🔒, the <strong>cost</strong> of finding and fixing the problem will <strong>always be free 🆓 🎉</strong></p>

  <p>That's the <strong><a class="primary" target="_blank" href="/promise">HD Promise™</a></strong></p>

  <p>If you're suddenly thinking hang on, 🤔 <strong>what exactly constitutes faulty code?</strong> Does that mean I am going to be charged for our mistakes? Then <strong>you need to read the <a class="primary" target="_blank" href="/promise">HD Promise™</a></strong></p>

  <p>It's essentially our service agreement. It lays out our <strong>technical terms</strong> , in <strong>plain English</strong>. As well as lots of information about who we are, how we work, and <strong class="green">what this whole platform is all about.</strong></p>

  <p class="mb-4"><strong>It answers questions like:</strong> What are the <strong>differences</strong> between the <strong>four types of lists?</strong></p>
  <%= render "shared/pros_and_cons_row" %>

  <p>It breaks down the <strong>confusing stuff</strong> into <strong>simple terms</strong>, like <strong>faulty code</strong> and how it concerns <strong>Emergency tasks</strong></p>

  <p class="mt-4"><strong>IN SIMPLE TERMS:</strong></p>

  <p class="mt-4">If <strong>we messed up</strong> , or you’re <strong>within your warranty</strong> -> Emergency To-do tasks are <span class="green"><strong>free</strong></span></p>

  <p>If <strong>we didn’t mess up</strong>, and your warranty <strong>has expired</strong> -> They’re not</p>

  <p class="mt-4"><strong>RESPECTIVE EXAMPLES OF BOTH:</strong></p>

  <p class="mt-4"><strong>We messed up:</strong> One of us left a comma in a file by mistake, which is caused the profile page to break</p>

  <p><strong>We didn’t mess up:</strong> Google change their map API service from free to paid and the map on the profile page stops working. (This actually happened in 2018! Millions of maps stopped working overnight.)</p>

  <p class="mt-4">Fingers crossed 🤞 neither of those emergencies would ever make it to this list if you had a <strong>support contract</strong> with Hoxton Digital.</p>
  <p>We stay up to date with all the latest tech news. Meaning we know about things like Google’s new API changes before they even go live.</p>

  <p>On top of that we also install <strong>AppSignal</strong> on all of our projects. It notifies us (and you too if you like) <strong>whenever an error occurs on a site</strong>. This means everyone knows about problems <strong>as soon as they occur</strong>, and we fix them before they can have an impact on users.</p>

  <p>If you hold a <strong>support contract</strong> with us, and something does go wrong outside of warranty, then the cost of fixing it will be <strong>deducted from your monthly support budget</strong> at the assigned HD developer’s normal hourly rate.</p>

  <p>However if you do not hold a support contract Hoxton Digital, then any time spent on Emergency Tasks will be billed upon completion. <strong>You will be charged 120%</strong> of the normal hourly rate of the HD developer you assign to the task.</p>

  <h4 class="mt-4 mb-4">Needless to say none of the maps on our supported sites went down back in 2018.</h4>

  <p>I have read the <%= link_to "HD promise™", promise_path %> and understand and accept the "Emergency List Terms” laid on therein</p>

  <%= simple_form_for (current_user) do |f| %>
    <%= f.input :accepts_promise, label: false, required: true %>
    <%= f.submit "Accept HD Promise and ACTIVATE LIST", class: 'btn btn-primary mt-2' %>
  <% end %>

</div>