config/routes.rb
Rails.application.routes.draw do
  get 'projects/:id/team_memberships', to: "projects#team_memberships"
  resources :team_memberships, only: [:destroy]
  authenticate :user, ->(user) { user.admin? } do
    root 'pages#developer', as: :admin_authenticated_root
  end
  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end
  devise_for :users
  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end
  resources :documents, except: [:new, :create, :edit, :update]
  resources :projects, except: [:destroy] do
    resources :team_memberships, only: [:create]
    resources :lists, only: [:new, :create, :index, :update]
    resources :documents, only: [:index, :new, :create, :edit, :update]
  end
  resources :quotes, except: [:new, :create] do
    member do
      patch :submit_for_acceptance
      patch :accept
      patch :reject
    end
    resources :tasks, only: [:create]
  end
  resources :lists, except: [:new, :create, :index, :update] do
    resources :quotes, only: [:new, :create]
    resources :tasks, only: [:new, :create] do
      member do
        get :complete
        get :uncomplete
      end
    end
  end
  resources :tasks, except: [:create, :new] do
    resources :periods, only: [:create, :new]
  end
  resources :notes, only: [:create, :update, :destroy]
  resources :periods, only: [:show, :update, :index] do
    member do
      patch :finish
      patch :accept
    end
  end
  get '/promise/', to: 'pages#promise'
  resources :invoices do
    member do
      patch :approve
    end
  end
  resources :users, only: [:edit, :update]
  get 'profile', to: 'pages#profile'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :dev_user, :class_name => "User"
  has_one :chatroom, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :tasks, through: :lists
  has_many :periods, through: :tasks
  has_many :invoices, dependent: :destroy
  has_many :team_memberships,  dependent: :destroy
  has_many :members, through: :team_memberships, source: :user
  validates :name, presence: true
  after_create :create_lists

  def initials
    name.split.map { |word| word[0].upcase }.join('')
  end

  def current_invoice
    self.invoices.order(created_at: :desc).first
  end

  def week_passes
    if self.current_invoice.tasks.any?
      self.current_invoice.update(approved: false, issued_at: Time.now)
      Invoice.create!(project: self, approved: nil, total: calculate_total)
    end
  end

  def calculate_total
    self.tasks.sum(&:total)
  end

  def deleteable_memberships
    team_memberships.where("priority > 2")
  end

  def valid_memberships
    team_memberships.select{|m| m.user.valid?}
  end

  def valid_members
    members.select{|m| m.valid?}
  end

  def paid_invoices
    invoices.order(due_by: :asc).where.not(paid_at: nil)
  end

  def unpaid_invoices
    invoices.order(due_by: :asc).where(paid_at: nil, issued_at: nil, approved: true)
  end

  def live_periods
    periods.where(end_time: nil)
  end

  def self.payment_types
    [
      ["emergency", "Emergency 🚨 -> If your site has gone down or something is breaking add it here. Your team will
       be notified immediately and the task will go to the top of their priority list."],
      ["quoted", "Quoted 🤝 -> New tasks will be quoted at a fixed price by the development team. If the quote is accepted
       by the project owner the task will be billed upon completion. Best for large features and major changes."],
      ["support", "Hourly ⏱️ -> Tasks will be started as soon as possible and billed at an hourly rate. Best for small changes to
       the site and stuff you want done fast."],
      ["my tasks", "My Tasks 🆓 -> This is a good list type to use for your own tasks or when you are testing out the platform for the first time."]
    ]
  end

  def week_passes

  end

  private

  def create_lists
    List.create!(name: "Emergencies", payment_type: "emergency", project: self)
    List.create!(name: "Support", payment_type: "support", project: self)
    List.create!(name: "Quoted", payment_type: "quoted", project: self)
    List.create!(name: "My tasks", payment_type: "my_tasks", project: self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :team_memberships]

  # GET /projects
  # GET /projects.json

  def index
    @projects = policy_scope(Project)
  end

  def team_memberships
    @memberships = @project.team_memberships
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    authorize @project
    project_params[:dev_user_id] ? @project.user = current_user : @project.dev_user = current_user
    respond_to do |format|
      if @project.save
        TeamMembership.create!(user: @project.user, relation: "client", project: @project)
        TeamMembership.create!(user: @project.dev_user, relation: "lead", project: @project)
        Invoice.create!(project: @project)
        Chatroom.create!(name: @project.name, project: @project)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.includes(team_memberships: [user: [photo_attachment: :blob]], lists: [:tasks]).find(params[:id])
      authorize @project
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:user_id, :dev_user_id, :name)
    end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <% if current_user.admin %>
      <%= f.association :user, collection: User.where(admin: false), prompt: "Which client is this project for?", label_method: :full_name, value_method: :id, include_blank: false, label: 'Client' %>
    <% else %>
      <%= f.association :dev_user, collection: User.where(admin: true), prompt: "Who would you like leading the project?", label_method: :full_name, value_method: :id, include_blank: false %>
    <% end %>
    <%= f.input :name, placeholder: "What shall we call it?" %>
  </div>






  <div class="jc mt-4">
    <%= f.button :submit, "Create Project", class: "btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="top-header rel">
  <h2><strong>Projects </strong></h2>
  <%= render 'shared/line', path: nil %>
</div>
<div class="container">
  <div class="row">
    <% if @projects.empty? %>
      <div class="col-sm-3 offset-sm-9 text-right">
        <h1>👆</h1>
        <h5>It looks like you haven't got any projects yet. Let's make your first one</h5>
      </div>
    <% else %>
      <% @projects.each do |project| %>
        <div class=" col-xs-12 col-lg-4 col-md-6">
          <div class="backed backed-sm back-hov">
            <h4 class="elipssis"><strong><%= project.name %></strong></h4>
            <h5 class="elipssis"><%= project.user.company %></h5>
            <div class="team-holder">
              <%= render "shared/member_row", memberships: project.valid_memberships, delete: false, hide_add: true %>
            </div>
            <%= link_to project_path(project) do %>
              <div class="link"></div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="top-header">
  <h2 class="text-center"><strong>New Project</strong></h2>
</div>
<div class="container">
  <div class="rhs-cont">
    <div class="row">
      <div class="col-sm-12 col-md-8 offset-md-2 offset-md-3 col-lg-6">
        <div class="backed">
          <div class="p-2">
            <h4 class="text-center mb-4"><strong>Let's start something special!</strong></h4>
            <%= render 'form', project: @project %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="top-header">
  <h1 class="text-center"><strong><%= @project.name %></strong></h1>
  <h3 class="text-center"><strong><%= @project.user.company %></strong></h3>
  <%= render "shared/member_row", memberships: @project.valid_memberships, delete: false, hide_add: false %>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <div class="backed">
        <h4 class="elipssis"><strong>Developing now</strong></h4>
        <hr>
        <div class="backed-inner">
          <%= render "shared/periods", periods: @project.live_periods %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <div class="backed">
        <h4 class="elipssis"><strong><%= link_to "To-dos", project_lists_path(@project), class: "secondary" %></strong>  <span style="font-size: 1.25rem;">✅</span></h4>
        <hr>
        <div class="backed-inner">
          <% @project.lists.each do |list| %>
            <h6>
              <%= link_to list_path(list), class: 'secondary' do %>
                 <span class="<%= 'green' if list.incomplete_tasks.length == 0  %>"><%= list.name %>
                  (<%= list.tasks.length - list.incomplete_tasks.length %>/<%= list.tasks.length %>)
                  <% if list.incomplete_tasks.length == 0 %>
                    <i class="fa fa-check-square"></i>
                  <% end %>
                </span>
              <% end %>
            </h6>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <%= link_to chatroom_path(@project.chatroom), class: "backed" do %>
        <h4 class="elipssis"><strong>Campfire</strong></h4>
        <hr>
        <div class="backed-inner">
          <!-- When messages are added, put an if statement here, e.g. if @messages.length > 0 else show this stuff👇 -->
          <p class="backed-emoji">🏕</p>
          <p class="text-center grey size-14">
            Chat casually with the team, ask random questions, and share stuff without ceremony.
          </p>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <div class="backed">
        <h4 class="elipssis"><strong>This Week</strong></h4>
        <hr>
        <div class="backed-inner">
        <p><strong>Total: <%= @project.current_invoice.humanized_total(@project.current_invoice.total_cents) %></strong></p>
          <% if @project.current_invoice.tasks.any? %>
            <% @project.current_invoice.tasks.each do |task| %>
              <div class="sub-backed">
                <p class='m-0'><%= task.name %> - <%= task.humanized_total(task.price) %></p>
                <%= link_to task_path(task), class: "link" do %>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <p class="backed-emoji">🗓️</p>
            <p class="text-center grey size-14">
              Tasks completed so far this week
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <div class="backed">
        <h4 class="elipssis"><strong>Invoices</strong></h4>
        <hr>
        <div class="backed-inner">
          <% if @project.unpaid_invoices.length > 0 %>
            <% @project.unpaid_invoices.each do |invoice| %>
              <div class="sub-backed <%= invoice.color %>">
                <p class='m-0'><%= 1001 + invoice.id %> - <strong>£ <%= invoice.total %></strong> <%= invoice.due_by > Time.now ? "due in" : "overdue by"  %> <%= distance_of_time_in_words(invoice.due_by - Time.now) %></p>
                <%= link_to invoice_path, class: "link" do %>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <p class="backed-emoji">⏰</p>
            <p class="text-center grey size-14">
              Invoices which have not yet been paid.
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 tight-grid">
      <%= link_to project_documents_path(@project), class: "backed" do %>
        <h4 class="elipssis"><strong>Documents</strong></h4>
        <hr>
        <div class="backed-inner">
          <p class="backed-emoji">📄</p>
          <p class="text-center grey size-14">
            Share docs, files, images, and spreadsheets. Organise in folders so they’re easy to find.
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/team_memberships.html.erb
<div class="top-header">
  <h2 class="text-center"><strong><%= link_to @project.name, project_path(@project), class: "secondary"  %>'s team</strong></h2>
  <%= render "shared/member_row", memberships: @project.valid_memberships, delete: false, hide_add: true %>
</div>
<div class="container">
  <div class="rhs-cont">
    <div class="row">
      <div class="col-sm-12 col-md-8 offset-md-2 offset-md-3 col-lg-6">
        <div class="backed">
          <div class="p-2">
            <h4 class=" text-center mt-2 mb-4"><strong>What would you like to do?</strong></h4>
            <h5 class="mt-2 mb-2">add an HD developer to the project</h5>
            <%= simple_form_for [@project, TeamMembership.new] do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs">
                <%= f.association :user, collection: User.where(admin: true) - @project.members.where(admin: true) , prompt: "Which developer would you like to add?", label_method: :full_name, value_method: :id, include_blank: false, label: false %>
              </div>






              <div class="jc mt-2 mb-5">
                <%= f.button :submit, "Add", class: "btn-primary" %>
              </div>
            <% end %>


            <h5 class="mt-2 mb-2">invite a new member with their email</h5>
            <%= simple_form_for [@project, TeamMembership.new] do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs">
                <%= f.input :email, placeholder: "e.g. barack@blacklivesmatter.com", label: false %>
              </div>
              <div class="jc mt-2 mb-5">
                <%= f.button :submit, "Invite", class: "btn-primary" %>
              </div>
            <% end %>
            <% if @project.deleteable_memberships.any? %>
              <h5>or remove a someone</h5>
              <%= render "shared/member_row", memberships: @project.deleteable_memberships, delete: true %>
            <% end %>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>